[cursor]
style = { shape = "block", blinking = "On" }
blink_interval = 500
blink_timeout = 0

[font]
size = 12

[general]
import = [ "~/.config/alacritty/themes/noctalia.toml"]

[window]
padding = { x = 16, y = 16 }
